version: "3.9"
services: 
    web_load_balancer:
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - "80:1234"
        environment:
            - NGINX_PORT=1234
        restart: always
    
    client_one:
        build:
            dockerfile: Dockerfile
            context: ./client/client-one
        volumes:
            - type: volume
              target: /app/node_modules
              volume:
                nocopy: true
            - type: bind
              source: ./client/client-one
              target: /app
        ports:
            - "1000:1000"

    server_one:
        build:
            dockerfile: Dockerfile
            context: ./server/server-one
        volumes:
            - type: volume
              target: /app/node_modules
              volume:
                nocopy: true
            - type: bind
              source: ./server/server-one
              target: /app
        ports:
            - "2000:2000"
        
             