version: "3.9"
services:

  web-nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: web-nginx
    ports: 
      - "80:80"
    networks: 
      - default
    environment:
      - NGINX_PORT=80
    #restart: always

networks: 
  default: